### ISSUE TITLE
Subscribe failed - no reason why!

### ISSUE THREAD

**Issue by PrasBiswas** [bitnami/bitnami-docker-prometheus#2]
Getting this error when I try to Subscribe to a Bitnami Prometheus Container Image:

Subscribing container image Prometheus Container Image to Azure Container Registry <MyPrometheusContainer> failed.

No reason provided why!

**Comment by beltran-rubo** [comment]
Hi @PrasBiswas 

We could not reproduce it on our side. Could you post which tag did you use to subscribe to the image? We tested the process using "latest" and it works well.

<img width="780" alt="Screen Shot 2019-08-05 at 12 35 51" src="https://user-images.githubusercontent.com/3718440/62458636-b95a2b00-b77d-11e9-9b97-c7cbcad0b816.png">

**Comment by PrasBiswas** [comment]
I tried latest, 2.10.0, 2.11.1, etc.

Sorry forgot to mention this is in **Azure**.

**Comment by beltran-rubo** [comment]
Thanks, we will report to the Azure team.

**Comment by beltran-rubo** [comment]
Hi @PrasBiswas 

There should be logs under “Activity log”. Could you please check them and paste here if there is any error/failure there?

**Comment by erikkurtu** [comment]
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-register-provider-errors

This helped me with the same problem

**Comment by carrodher** [comment]
Thanks for sharing this information, I'm sure it will help other users
